modules:
  - type: script
    snippets:
      - "curl https://brave-browser-rpm-release.s3.brave.com/brave-core.asc > /etc/pki/rpm-gpg/brave-core.asc"
  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      - brave-browser
    optfix:
      - brave.com
