modules:
  - type: files
    files:
      - usr:
          /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      - powertop
      - tailscale
      - fish
      - wl-clipboard
      - git-lfs

      - rclone
      - restic

      - kernel-tools # Needed for cpupower and turbostat
      - python3-pyudev # Needed for AMD S2Idle Debug Script
      - acpica-tools # Needed for AMD S2Idle Debug Script
      # tuned, copied roughly from Bluefin
      - tuned
      - tuned-ppd
      - tuned-utils
      - tuned-profiles-atomic

      - virt-manager
      - virt-viewer
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - qemu

      - brave-browser
    remove:
      - power-profiles-daemon
  - type: systemd
    system:
      enabled:
        - tuned.service

  - type: script
    scripts:
      - amdgpu_top.sh
      # - update_firmware.sh
      # - mesa_git.sh
