# image will be published to ghcr.io/<user>/<name>
name: nulo-os-aurora-dx
description: Aurora DX - Nulo's version

base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - from-file: common-brave.yml
  - type: rpm-ostree
    install:
      - foo2zjs
      - foo2xqx
      - git-lfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
