# image will be published to ghcr.io/<user>/<name>
name: kinoite-fw13-amd
description: Kinoite for the Framework 13 - AMD 7040 Series

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# https://github.com/achhabra2/fw13-amd-kinoite/blob/live/config/recipe.yml

modules:
  - type: files
    files:
      - usr:
          /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/mariolimonciello/power-profiles-daemon/repo/fedora-%OS_VERSION%/mariolimonciello-power-profiles-daemon-fedora-%OS_VERSION%.repo
    install:
      - powertop
      - tailscale
      - fish
      - kernel-tools # Needed for cpupower and turbostat
      - python3-pyudev # Needed for AMD S2Idle Debug Script
      - acpica-tools # Needed for AMD S2Idle Debug Script
      - rocm-hip
      - rocm-opencl
      - rocm-clinfo

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - amdgpu_top.sh
      - power_profiles_daemon.sh
      # - update_firmware.sh
      # - mesa_git.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
